### ISSUE TITLE
Hogar Touch Panel

### ISSUE THREAD

**Issue by biggy5252** [AutomateAsia/com.hogarcontrols#1]
I tried to add the 
HTP-1SH-UK = 1 Touch Panel Switch High Power on the Homey devices using the hogarcontrol app, but I get the following error status.missing_multiChannelNodeID_1_on_node

Is there a way you can help solve this, and/or add this product into the product list and/or advise who it can be added from my side. 

Thanks

**Comment by limkopi78** [comment]
We have fixed the issue on 1 button switch and published the app.

**Comment by biggy5252** [comment]
I haven't seen he updated app on the athom page. Does it take time?

Also how can we incorporate other Hogar devices like their sensors and alarms?

**Comment by limkopi78** [comment]
Hi,

It will take a few days for Athom to approve the change. For other devices,
we will need the physical devices to incorporate them.

**Comment by biggy5252** [comment]
Thank you for the update. 

Do you need anything specific from the device which I can help you with? I will have all the physical items as sample pieces with me by next month. 

If you guide me on what technical data you need from the device, I will be more thank happy to collaborate with you to add support for all these devices.

**Comment by biggy5252** [comment]
I can confirm the update of the app has solved the problem, Thank you very much. 

Still awaiting to hear from you on if we can work together on developing and adding more Hogar items to the list.

**Comment by limkopi78** [comment]
Done with the adding of 2 devices :)

**Comment by ashleywolf87** [comment]
may I know if the Hogar 3-Touch and 4-Touch Panel Switch are compatible with Homey right out of the box or would I need to perform some modifications?

**Comment by limkopi78** [comment]
No modifications needed.
